CC = gcc
main:
	$(CC) -o main ../src/main.c ../src/console.c 

# Sementara biar mudah ngerun
start:
	$(CC) -o start ../src/ADT/mesin/mesinkata.c ../src/ADT/mesin/mesinkalimat.c ../src/ADT/mesin/mesinkarakter.c ../src/ADT/map2/map2.c ../src/command/start.c

console:
	$(CC) -o console ../src/ADT/mesin/mesinkata.c ../src/ADT/mesin/mesinkalimat.c ../src/ADT/mesin/mesinkarakter.c ../src/ADT/map2/map2.c ../src/command/start.c ../src/command/list.c ../src/console2.c

list:
	$(CC) -o list ../src/ADT/mesin/mesinkata.c ../src/ADT/mesin/mesinkalimat.c ../src/ADT/mesin/mesinkarakter.c ../src/ADT/map2/map2.c ../src/command/list.c ../src/command/start.c